DROP TABLE taxon_hierarchy
;
CREATE TABLE taxon_hierarchy
 	(taxon_level	NUMBER(2)	NOT NULL
	,taxon_name	VARCHAR2(18)	NOT NULL   )
 STORAGE (INITIAL 32K NEXT 32K PCTINCREASE 0) PCTFREE 5
 TABLESPACE DATA_SMALL
 NOLOGGING
;
